name: Deploy dev

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monitor
        uses: actions/checkout@v3
        with:
          repository: HSLdevcom/transitlog-monitor
          ref: dev
      - name: Build monitor and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/transitlog-monitor
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tags: dev
